version: "3"
volumes:
  static:
  media:

services:
  postgres:
    image: postgres:13.3
    env_file: .env
    ports:
      - "5432:5432"

  backend:
    build: ./apple/
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - static:/backend_static/static
      - media:/media/
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py loaddata db.json &&
             python manage.py initadmin &&
             python manage.py runserver 0.0.0.0:8000"