# Generated by Django 5.1.6 on 2025-03-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='updated_at',
        ),
    ]
