# Generated by Django 5.1.6 on 2025-03-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_remove_shoppingcart_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='ID Пользователя'),
        ),
    ]
