# Generated by Django 5.1.6 on 2025-03-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_telegramuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.PositiveIntegerField(default=10, verbose_name='В наличии'),
        ),
    ]
